type: prometheus
datasource: 'Prometheus (prod)'
# metrics_prefix: 'prometheus_'
description: Dashboard for Tarantool application and database server monitoring, based on grafonnet library.
grafana_tags: [tarantool]
sections:
  - cluster
  - cpu

title: UCP Tarantool Dashboard

alerts:
  getrusage_cpu_user_time:
    name: test alert
    for: 5m
    frequency: 5m
    message: Bad requests / All requests ratio exceeded
    notifications:
      - uid: zVZ-YmoVz
    conditions:
      - evaluator:
          params:
            - 0.05
          type: gt
          operator:
            type: and
          query:
            params:
              - A
              - 10m
              - now
          reducer:
            params:
            type: avg
          type: query # need default , it's dificult since conditions is a list



